version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: tester
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
