# Generated by Django 3.0.8 on 2020-07-22 20:44

from django.db import migrations

from ..models import Symbol


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Account',
        ),
    ]
