# Generated by Django 3.0.8 on 2020-07-27 21:13

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200723_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='api.Symbol'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.Symbol'),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.CharField(default=api.models.random_order_id, max_length=10, primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(default=None, max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='api.Symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='api.User')),
            ],
        ),
    ]
