# Generated by Django 3.0.8 on 2020-08-03 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200727_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='commission',
            field=models.DecimalField(decimal_places=8, default='0.005', max_digits=15),
        ),
        migrations.AddField(
            model_name='symbol',
            name='min_withdraw',
            field=models.DecimalField(decimal_places=8, default='0.01', max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='frozen',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(default=None, max_length=66, null=True)),
                ('address', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('commission_service', models.DecimalField(decimal_places=8, max_digits=15)),
                ('commission_blockchain', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='api.Symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='api.User')),
            ],
        ),
    ]
