# Generated by Django 3.0.8 on 2020-08-03 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


def add_symbol_brokers(apps, schema_editor):
    brokers = [
        'Сбербанк', 'Тинькофф', 'ВТБ', 'Альфа-Банк', 'Приват-Банк',
        'Каспий-Банк', 'Газпромбанк', 'Банк Открытие',
        'QIWI', 'Яндекс', 'ADV cash', 'Payeer', 'Банковский перевод'
    ]
    Broker = apps.get_model("api", "Broker")
    db_alias = schema_editor.connection.alias
    objects = [Broker(name=name) for name in brokers]
    Broker.objects.using(db_alias).bulk_create(objects)

    Symbol = apps.get_model("api", "Symbol")
    db_alias = schema_editor.connection.alias
    Symbol.objects.using(db_alias).create(name='eth', min_withdraw=0.01, commission=0.005)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200803_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 3, 21, 19, 52, 785402, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(add_symbol_brokers)
    ]
