# Generated by Django 3.0.8 on 2020-08-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deal_requisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='api.Deal')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='api.User')),
            ],
            options={
                'unique_together': {('user', 'target', 'deal')},
            },
        ),
    ]
