# Generated by Django 3.0.8 on 2020-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_nickname_change',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
