# Generated by Django 3.0.8 on 2020-09-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200825_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='initiator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.User'),
            preserve_default=False,
        ),
    ]
