# Generated by Django 3.0.8 on 2020-09-03 20:22

from django.db import migrations, models

from api.models import Symbol



def add_symbols(*args):
    Symbol.objects.create(name='usdt', min_withdraw=10, commission=5)
    Symbol.objects.create(name='prizm', min_withdraw=10, commission=1)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dispute_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.RunPython(add_symbols)
    ]
