# Generated by Django 3.0.8 on 2020-09-04 15:46

from django.db import migrations

from api.models import Symbol


def add_symbols(*args):
    Symbol.objects.create(name='btc', min_withdraw=0.01, commission=0.0005)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200903_2022'),
    ]

    operations = [
        migrations.RunPython(add_symbols)
    ]
