# Generated by Django 3.0.8 on 2020-09-04 15:46

from django.db import migrations


def add_symbols(apps, schema_editor):
    Symbol = apps.get_model("api", "Symbol")
    db_alias = schema_editor.connection.alias
    Symbol.objects.using(db_alias).create(name='btc', min_withdraw=0.001, commission=0.0005)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200903_2022'),
    ]

    operations = [
        migrations.RunPython(add_symbols)
    ]
