# Generated by Django 3.0.8 on 2020-09-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200904_1546'),
    ]

    operations = [
        migrations.RunSQL('DELETE FROM api_deposit'),
        migrations.AddField(
            model_name='deposit',
            name='address',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
