# Generated by Django 3.0.8 on 2020-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_deposit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='deals_commission',
            field=models.DecimalField(decimal_places=5, default=0.001, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_part',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=6),
        ),
    ]
