# Generated by Django 3.0.8 on 2020-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200914_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='min_withdraw',
            new_name='min_transaction',
        ),
        migrations.AddField(
            model_name='account',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
    ]
