# Generated by Django 3.0.8 on 2020-09-20 14:37

from django.db import migrations, models


def update_ref(apps, schema_editor):
    User = apps.get_model("api", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).update(ref_part=0.3)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200916_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_part',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=6),
        ),
        migrations.RunPython(update_ref)
    ]
