# Generated by Django 3.0.8 on 2020-09-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200920_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amount_crypto_blocked',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='amount_crypto_send',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
