# Generated by Django 3.0.8 on 2020-09-24 07:45

from django.db import migrations


def update_broker(apps, schema_editor):
    Broker = apps.get_model("api", "Broker")
    db_alias = schema_editor.connection.alias
    Broker.objects.using(db_alias).filter(name='Банковский перевод').update(name='Прочее')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200922_1928'),
    ]

    operations = [
        migrations.RunPython(update_broker)
    ]
