# Generated by Django 3.0.8 on 2020-09-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200924_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
