# Generated by Django 3.0.8 on 2020-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_symbol_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='add_info',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='requisite',
            name='add_info',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
