# Generated by Django 3.0.8 on 2020-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200925_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='add_info',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='requisite',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
