# Generated by Django 3.0.8 on 2020-09-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200925_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coefficient',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
