# Generated by Django 3.0.8 on 2020-11-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(),
        ),
    ]
