SELECT_BROKER = 'SELECT_BROKER'
CHOOSE_LIMITS = 'CHOOSE_LIMITS'
CHOOSE_RATE = 'CHOOSE_RATE'

WITHDRAW_CHOOSE_ADDRESS = 'wCHOOSE_ADDRESS'
WITHDRAW_CHOOSE_AMOUNT = 'wCHOOSE_AMOUNT'

EDIT_ORDER_LIMITS = 'EDIT_ORDER_LIMITS'
EDIT_ORDER_RATE = 'EDIT_ORDER_RATE'
EDIT_ORDER_DETAILS = 'EDIT_ORDER_DETAILS'
ORDER_DELETE = 'ORDER_DELETE'

EDIT_REQUISITE = 'EDIT_REQUISITE'

BEGIN_DEAL_ENTER_AMOUNT = 'BEGIN_DEAL_ENTER_AMOUNT'
CONFIRM_BEGIN_DEAL = 'CONFIRM_BEGIN_DEAL'

SEND_MESSAGE = 'SEND_MESSAGE'

NICKNAME_CHANGE = 'NICKNAME_CHANGE'
